### ISSUE TITLE
[Feature Request]: Allow to open the image immediately, without the intermediate page

### ISSUE THREAD

**Issue by tkzv** [foooomio/view-background-image#41]
### Description

Please return the behaviour of the old versions.

**Comment by SudosFTW** [comment]
> ### Description
> 
> Please return the behaviour of the old versions.

This. I don't understand why there's a difference in behavior unless it's to put multuple "background image" assets on one tab, but this should be something that is able to be toggled on and off at will in the extension settings. extra clicks make people upset and I'm also definitely one of these people as well.

If this is to bring forth the donate button, then I understand, but there should still be a way to turn it off as most users are going to see this as a nag screen more than anything.

**Comment by foooomio** [comment]
Hi, thank you for your opinion.

I decided to change the behavior for two reasons:

1. To avoid opening too many tabs when multiple images are obtained. Can you tell me under what circumstances the extra clicks occur? If you want the URL of an image, you can get it from the context menu without selecting the location bar.
2. Firefox prohibits opening Data URLs at the top level for security reasons. The new viewer resolves this. It is assumed that Chrome and Edge will do the same in the future. See this blog post for more details. https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-59/

I would like to avoid adding settings to the extension because it would require new permission from the user.

I guess you don't like the donate button, but it is important. I've been spending a lot of time on the extension. I've received many emails asking me to buy the extension. If I accept them, I'll get some money, but the extension will be modified to collect your personal information. That's why your donation matters.

Thank you for your understanding.

**Comment by tkzv** [comment]
> 1. Can you tell me under what circumstances the extra clicks occur?

I open multiple images from t.me, then save them one by one with Ctrl-S or with an extension that saves multiple tabs. Extensions that save images from HTML pages do not work with cdn-telegram.org, thus with the new version I need to click each image to open it without the HTML page.

**Comment by foooomio** [comment]
Thank you for your reply!

How about adding a download button to the viewer? I think this feature will resolve your issue without other extensions.

I'll check if this feature can be implemented. Thank you for inspiring me with the idea of a new feature!

**Comment by tkzv** [comment]
> How about adding a download button to the viewer?

Same problem — an extra click on every page.

**Comment by foooomio** [comment]
I'm thinking of a button that compresses and downloads all o the images. Not enough?

Also, can I hear your opinion @SudosFTW ?

**Comment by foooomio** [comment]
Alternatively, how about adding a button to the viewer that displays all of the images in separate tabs? Yes, it requires an extra click, but this is the compromise.

It turns out that new permission is required to allow images to be downloaded. I would like to avoid it.

The extension is not intended to be used in the way you do. I can't give you special treatment.

**Comment by tkzv** [comment]
Your extension used to do only one thing, but did it right. Which made it very useful.

The new version only excels at drawing attention to "Donate" button.

**Comment by foooomio** [comment]
@tkzv https://github.com/foooomio/view-background-image/issues/41#issuecomment-2138698422

> I guess you don't like the donate button, but it is important. I've been spending a lot of time on the extension. I've received many email offering to buy the extension from me. If I accept them, I'll get some money, but the extension will be modified to collect your personal information. That's why your donation matters.

And I've offered the compromise and if you don't have an opinion on it, I won't implement it.

**Comment by foooomio** [comment]
@tkzv @SudosFTW Don't you have any opinions?

Let's have a constructive debate. It's easy to complain.

Be thankful that I spend my time on free riders like you who do nothing but complain.

**Comment by tkzv** [comment]
What's there to discuss? The new version no longer has any significant advantages over "Search by Image", which handles overlapping images better. Furthemore, "View Background Image" stopped working in Firefox 115.11.0esr. I simply switched to "Search by Image".

**Comment by foooomio** [comment]
Seems like a waste of time to talk to you. Closing.

**Comment by regs01** [comment]
I'm using this addon together with Better Image Viewer extension. And version 3 requires additional clicks.  I didn't care about multiple tabs opened at some times. As it's not happening always and anyway i'm getting straight to viewer. But worst part of it, is that it just doesn't work at all in Linux. Version 2 does work flawlessly.

**Comment by foooomio** [comment]
@regs01 Can you create a new issue?

**Comment by MarekBodinger** [comment]
[view-background-image-2.10.4.zip](https://github.com/user-attachments/files/16254171/view-background-image-2.10.4.zip)

Here's an old version that opened the images in new tabs with manifest updated to the latest version to ensure compatibility in the future.

You can [install it as unpacked extension](https://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system).

**Comment by regs01** [comment]
> [view-background-image-2.10.4.zip](https://github.com/user-attachments/files/16254171/view-background-image-2.10.4.zip)
> 
> Here's an old version that opened the images in new tabs with manifest updated to the latest version to ensure compatibility in the future.
> 
> You can [install it as unpacked extension](https://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system).

In case of Firefox you can install 2.10.4 right from AMO
https://addons.mozilla.org/ru/firefox/addon/view-background-images/versions/
